Search endpoint required to find person id from email
malomohq/klaviyo-elixir pull request #43
Opened 2022-06-14 08:14 UTC by msaurabhee

Please approve this PR and publish the build for the new version,
so that I can use this endpoint.

Thanks.

2022-07-01 05:57 UTC, msaurabhee commented
Can some one approve and merge this? Anyone? What does a guy have to do to get his PR merged around here?

2022-07-01 15:25 UTC, anthonator requested changes

2022-07-04 04:46 UTC, msaurabhee commented on lib/klaviyo/helpers/url.ex
> +  defp put_query(uri, %{ method: :put } = operation, _config) do
Sorry, I ran a request with `:PUT`, it is not working here. So while debugging, I found that the `url` field was not being evaluated with `api_key` parameter. After this modification, PUT started working.

I guess, klaviyo servers expect `api_key` as a parameter in PUT requests.

2022-07-04 08:25 UTC, msaurabhee commented on lib/klaviyo/helpers/url.ex
> +  defp put_query(uri, %{ method: :put } = operation, _config) do
@anthonator can you try any `PUT` requests with current master against actual Klaviyo subscription? I was trying against this function:

```
  @doc """
  Update member
  """
  def update_member(person_id, attrs, api_key) do
    with {:ok, response} <-
           Klaviyo.Person.update(person_id, attrs)
           |> Klaviyo.request(%{private_api_key: api_key}) do
      person = Map.get(response, :body)
      {:ok, person}
    end
  end
```

The test is as follows:
```
  describe "update_member" do

    test "update existing member" do
      api_key = "replace_with_api_key"
      person_id = "replace_with_profile_id"
      attrs = %{"external_id" => "", "$id" => "some_id"}

      assert {:ok, %{"id" => ^person_id}} =
               KlaviyoAdapter.update_member(person_id, attrs, api_key)
    end
  end
```

2022-07-06 13:05 UTC, anthonator commented on lib/klaviyo/helpers/url.ex
> +  defp put_query(uri, %{ method: :put } = operation, _config) do
Would you mind making this a separate pull request? This seems like a separate concern and I'd like to get `Klaviyo.People.search/1` released for you.

2022-07-07 06:57 UTC, msaurabhee commented on lib/klaviyo/helpers/url.ex
> +  defp put_query(uri, %{ method: :put } = operation, _config) do
There you go @anthonator https://github.com/malomohq/klaviyo-elixir/pull/44/files

2022-07-13 04:15 UTC, msaurabhee commented on lib/klaviyo/helpers/url.ex
> +  defp put_query(uri, %{ method: :put } = operation, _config) do
@anthonator can you try out the PUT requests as described in the above request against master, and let me know, if this PR can be merged or not? The `PUT` requests don't work as per me.

2022-07-25 09:34 UTC, msaurabhee commented on lib/klaviyo/helpers/url.ex
> +  defp put_query(uri, %{ method: :put } = operation, _config) do
@anthonator any updates on this, please?

2022-08-20 13:01 UTC, msaurabhee commented on lib/klaviyo/helpers/url.ex
> +  defp put_query(uri, %{ method: :put } = operation, _config) do
@anthonator any updates on this, please (2)?

2023-03-06 20:10 UTC, anthonator commented
This should be handled by the most recent rewrite.

2023-03-06 20:10 UTC, closed without merging